### ISSUE TITLE
Multisite compatibility?

### ISSUE THREAD

**Issue by ahmed-sigmalux** [nierdz/flush-opcache#1]
WP Opcache appears to have separate settings for each site in a multisite network. Since all the sites are operating on the same root domain, shouldn't there be a single WP Opcache network setting only? The Opcache needs to be flushed a single time, not once for each site in a multisite network.

**Comment by nierdz** [comment]
The plugin was not multisite compatible, I never tried it on multisite before today.
I just released a new version (2.2) to resolve this issue.
In multisite mode, only super admin can see option page and flush button in admin bar.
Can you try it and let me know if you have other problem ?

**Comment by ahmed-sigmalux** [comment]
Thanks for releasing an update and restricting the OPcache flush to super admins.

Does the "Automatically flush OPcache after an upgrade" setting run once per network or once per site in a multisite network?

**Comment by nierdz** [comment]
As far as I know, there is no update per site cause files are shared across all sites. Maybe I'm wrong, I'm not really familiar with WordPress MS...
All i can tell is I use this WordPress hook : [upgrader_process_complete](https://codex.wordpress.org/Plugin_API/Action_Reference/upgrader_process_complete) to flush OPcache after an update.
