### ISSUE TITLE
Question with memory peak

### ISSUE THREAD

**Issue by Membele** [nierdz/flush-opcache#12]
Hello, first of all, thank you for the plugin.

I have a problem, and I don't know if it's a problem or if it has to be that way.

When I flush the web OP cache, the memory peak drops to a minimum and the page speed is optimal, but after a little time, this memory spike doubles and the page runs slower.

I'm going to send you a screenshot of Query Monitor so you can see what I'm saying.

![hJBdM](https://user-images.githubusercontent.com/5517913/101027838-dae94380-3578-11eb-8b14-e861032e4e7a.jpg)
![lYkBB](https://user-images.githubusercontent.com/5517913/101027842-dcb30700-3578-11eb-96bb-d58f1f7450ba.jpg)

**Comment by nierdz** [comment]
Sorry, I just saw your issue !
This is not related to this plugin cause OPcache dit not change weight of the final page as show in your screenshots but I'm assuming you found this answer sooner...
